import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import dotenv from "dotenv";
dotenv.config();
import fs from "fs";
import path from "path";


const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	// copy the built plugin to the obsidian plugins folder
	if (!fs.existsSync(path.join(process.env.OBSIDIAN_PLUGINS_PATH, "smart-connections-graph-view"))) {
		fs.mkdirSync(path.join(process.env.OBSIDIAN_PLUGINS_PATH, "smart-connections-graph-view"));
	}
	fs.copyFileSync("./main.js", path.join(process.env.OBSIDIAN_PLUGINS_PATH, "smart-connections-graph-view/main.js"));
	fs.copyFileSync("./manifest.json", path.join(process.env.OBSIDIAN_PLUGINS_PATH, "smart-connections-graph-view/manifest.json"));
	fs.copyFileSync("./styles.css", path.join(process.env.OBSIDIAN_PLUGINS_PATH, "smart-connections-graph-view/styles.css"));
}

